[project]
name = "df06-calculator-samybenjelloun"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[project.scripts]
calculate = "df06_calculator_samybenjelloun.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
